/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author pazuti
 */
public class MainPanel extends javax.swing.JPanel
{

   /**
    * Creates new form MainPanel
    */
   public MainPanel()
   {
      initComponents();
      carregaAlunos();
      carregaTurmas();
   }
   
    /**
     *
     * @param panel
     */
    public MainPanel(javax.swing.JPanel panel)
   {
      this.superPanel = panel;
      initComponents();
      carregaAlunos();
      carregaTurmas();
   }
   
   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftBarPanel = new javax.swing.JPanel();
        studentButton = new javax.swing.JButton();
        classButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        importExportButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        welcomePanel1 = new Interface.WelcomePanel();
        classPanel1 = new Interface.ClassPanel();
        importPanel1 = new Interface.ImportPanel();
        personalInformationPanel1 = new Interface.PersonalInformationPanel();
        sendPanel1 = new Interface.SendPanel();
        studentPanel1 = new Interface.StudentPanel();
        testPanel1 = new Interface.TestPanel();
        exportPanel1 = new Interface.HelpPanel();

        leftBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentButton.setText("<html><center>Aluno</center></html>");
        studentButton.setPreferredSize(new java.awt.Dimension(57, 30));
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 145, 75));

        classButton.setText("<html><center>Turma</center></html>");
        classButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(classButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 76, 145, 75));

        testButton.setText("<html><center>Avaliações</center></html>");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(testButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 153, 145, 75));

        importExportButton.setText("<html>Importar/Exportar</html>");
        importExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importExportButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(importExportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 145, 75));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 461, 145, 75));

        sendButton.setText("Enviar");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        leftBarPanel.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, 145, 75));

        jButton1.setText("Ajuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        leftBarPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 384, 145, 75));

        displayPanel.setLayout(new java.awt.CardLayout());
        displayPanel.add(welcomePanel1, "cardWelcome");
        displayPanel.add(classPanel1, "cardClass");
        displayPanel.add(importPanel1, "cardImport");
        displayPanel.add(personalInformationPanel1, "cardPersonalInformation");
        displayPanel.add(sendPanel1, "cardSend");
        displayPanel.add(studentPanel1, "cardStudent");
        displayPanel.add(testPanel1, "cardTest");
        displayPanel.add(exportPanel1, "cardHelp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(leftBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardStudent");
    }//GEN-LAST:event_studentButtonActionPerformed

    private void classButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classButtonActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardClass");
    }//GEN-LAST:event_classButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardTest");
    }//GEN-LAST:event_testButtonActionPerformed

    private void importExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importExportButtonActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardImport");
    }//GEN-LAST:event_importExportButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
       CardLayout card = (CardLayout) superPanel.getLayout();
       card.show(superPanel, "cardLogin");
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardSend");
    }//GEN-LAST:event_sendButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CardLayout card = (CardLayout) displayPanel.getLayout();
       card.show(displayPanel, "cardHelp");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classButton;
    private Interface.ClassPanel classPanel1;
    private javax.swing.JPanel displayPanel;
    private Interface.HelpPanel exportPanel1;
    private javax.swing.JButton importExportButton;
    private Interface.ImportPanel importPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel leftBarPanel;
    private javax.swing.JButton logoutButton;
    private Interface.PersonalInformationPanel personalInformationPanel1;
    private javax.swing.JButton sendButton;
    private Interface.SendPanel sendPanel1;
    private javax.swing.JButton studentButton;
    private Interface.StudentPanel studentPanel1;
    private javax.swing.JButton testButton;
    private Interface.TestPanel testPanel1;
    private Interface.WelcomePanel welcomePanel1;
    // End of variables declaration//GEN-END:variables
   public static ArrayList<dsproject.Aluno> alunosLidos;
   public static ArrayList<dsproject.Turma> turmasLidas;
   private javax.swing.JPanel superPanel;

   public final void carregaAlunos()
   {
      File arquivoAlunos = new File("alunos.txt");
      FileInputStream arquivo;
      ObjectInputStream in;
      if (arquivoAlunos.exists())
      {
         try
         {
            arquivo = new FileInputStream(arquivoAlunos);
            in = new ObjectInputStream(arquivo);
            alunosLidos = (ArrayList<dsproject.Aluno>) in.readObject();
         }
         catch (IOException | ClassNotFoundException ex)
         {
            System.err.println(ex);
         }
      }
      else
      {
         alunosLidos = new ArrayList<>();
      }
   }
   
   public final void carregaTurmas()
   {
      File arquivoTurma = new File("turmas.txt");
      FileInputStream arquivo;
      
      ObjectInputStream in;
      if (arquivoTurma.exists())
      {
         try
         {
            arquivo = new FileInputStream(arquivoTurma);
            in = new ObjectInputStream(arquivo);
            turmasLidas = (ArrayList<dsproject.Turma>) in.readObject();
         }
         catch (IOException | ClassNotFoundException ex)
         {
            System.err.println(ex);
         }
      }
      else
      {
         turmasLidas = new ArrayList<>();
      }
   }
}
