/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dsproject.Escola;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author pazuti, Israel
 */
public class NewTeacherPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewTeacherPanel
     */
    public NewTeacherPanel() {
        initComponents();
    }

    public NewTeacherPanel(JPanel superPanel) {
        this.superPanel = superPanel;
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private javax.swing.JPanel superPanel;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cpf = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        senha = new javax.swing.JLabel();
        confsenha = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        passwordField = new javax.swing.JPasswordField();
        confirmaPasswordField = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(984, 536));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cpf.setText("CPF");
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        name.setText("Nome Completo");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 88, -1, -1));
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 83, 427, -1));

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 201, 85, -1));

        senha.setText("Senha");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 127, -1, -1));

        confsenha.setText("Confirmar Senha");
        jPanel1.add(confsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 166, -1, -1));

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 201, 85, -1));
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 45, 427, -1));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 122, 427, -1));
        jPanel1.add(confirmaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 161, 427, -1));

        jTabbedPane1.addTab("Cadastrar Professor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        cpf.setForeground(Color.black);
        name.setForeground(Color.black);

        senha.setForeground(Color.black);
        errorflag = false;
        //Troquei os tipos dos campos pra formattedTextField e PasswordField
        //erroscadlist = Escola.getInstance().cadastrarProfessor(cpfTextField.getText(),nameTextField.getText(),
        //                          passwTextField.getText(),confPassTextField.getText());
        
        System.out.println("tamanho - " + erroscadlist.size());
        
        for(int k =0 ; k< erroscadlist.size();k++){
            System.out.println(erroscadlist.get(k));
        }
        
        int error;
       
        if(erroscadlist.get(0).equals(0)){
            // sem erros - tudo lindo
            CardLayout card =  (CardLayout) this.superPanel.getLayout();
            card.show(this.superPanel,"cardLogin");
            return;//tem que vewr se precisa return
        }else{
            for(int i =0 ; i< erroscadlist.size();i++){
                error = erroscadlist.get(i);
                switch(error)
                {
                    case(1):
                        //erro cpf
                        cpf.setForeground(Color.red);
                        break;
                    case(2):
                        // error nome
                        name.setForeground(Color.red);
                        break;
                    case(7):
                        // erro senha
                        senha.setForeground(Color.red);
                        break;
                }         
            }
        }
         
    }//GEN-LAST:event_saveButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
            CardLayout card =  (CardLayout) this.superPanel.getLayout();
            card.show(this.superPanel,"cardLogin");
    }//GEN-LAST:event_voltarButtonActionPerformed

    private ArrayList<Integer> erroscadlist ;
    private boolean errorflag;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmaPasswordField;
    private javax.swing.JLabel confsenha;
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel senha;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
