/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dsproject.Escola;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JFrame;  
import javax.swing.JFormattedTextField;  
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter; 

/**
 *
 * @author pazuti, Israel
 */
public class NewTeacherPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewTeacherPanel
     */
<<<<<<< HEAD
    public NewTeacherPanel() {
=======
    public NewTeacherPanel()  {
>>>>>>> 5f95eb8927651a9138268c9f63d43167613d34ab
        initComponents();
       // cpfmask = new MaskFormatter("###.###.###-##");
       // campoFormatadoCpf =  new JFormattedTextField(cpfmask);
        //cpfmask.setValidCharacters("0123456789");  
        
        
    }

    
    public NewTeacherPanel(JPanel superPanel) {
        this.superPanel = superPanel;
        initComponents();
        //cpfmask = new MaskFormatter("###.###.###-##");
        //campoFormatadoCpf =  new JFormattedTextField(cpfmask);
        //cpfmask.setValidCharacters("0123456789");  
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private javax.swing.JPanel superPanel;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelCpf = new javax.swing.JLabel();
        labelNomeCompleto = new javax.swing.JLabel();
        campoNomeCompleto = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        labelSenha = new javax.swing.JLabel();
        labelConfirmarSenha = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        campoFormatadoCpf = new javax.swing.JFormattedTextField();
        campoPasswordSenha = new javax.swing.JPasswordField();
        campoPasswordConfirmarSenha = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(984, 536));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCpf.setText("CPF");
        jPanel1.add(labelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        labelNomeCompleto.setText("Nome Completo");
        jPanel1.add(labelNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 88, -1, -1));

        campoNomeCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeCompletoKeyTyped(evt);
            }
        });
        jPanel1.add(campoNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 83, 427, -1));

        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 201, 85, -1));

        labelSenha.setText("Senha");
        jPanel1.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 127, -1, -1));

        labelConfirmarSenha.setText("Confirmar Senha");
        jPanel1.add(labelConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 166, -1, -1));

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 201, 85, -1));

        campoFormatadoCpf.setFormatterFactory(setFormatoData());
        campoFormatadoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFormatadoCpfActionPerformed(evt);
            }
        });
        campoFormatadoCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoFormatadoCpfKeyTyped(evt);
            }
        });
        jPanel1.add(campoFormatadoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 45, 427, -1));
        jPanel1.add(campoPasswordSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 122, 427, -1));
        jPanel1.add(campoPasswordConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 161, 427, -1));

        jTabbedPane1.addTab("Cadastrar Professor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //cpf.setForeground(Color.black);
        //name.setForeground(Color.black);

        //senha.setForeground(Color.black);
        errorflag = false;
        //Troquei os tipos dos campos pra formattedTextField e PasswordField
        //erroscadlist = Escola.getInstance().cadastrarProfessor(cpfTextField.getText(),nameTextField.getText(),
        //                          passwTextField.getText(),confPassTextField.getText());
        
        char[] password = campoPasswordSenha.getPassword();
        char[] confirmPassword = campoPasswordConfirmarSenha.getPassword();
        String strPassword = new String(password);
        String strConfirmPassword = new String(confirmPassword);
        System.out.println("cpf cadastro -"+campoFormatadoCpf.getText());
        erroscadlist = Escola.getInstance().cadastrarProfessor(campoFormatadoCpf.getText(), campoNomeCompleto.getText(), strPassword, 
                                                               strConfirmPassword);
        
        //System.out.println("tamanho - " + erroscadlist.size());
        
        for(int k =0 ; k< erroscadlist.size();k++){
            System.out.println(erroscadlist.get(k));
        }
        
        int error;
       
        if(erroscadlist.get(0).equals(0)){
            // sem erros - tudo lindo
            CardLayout card =  (CardLayout) this.superPanel.getLayout();
            card.show(this.superPanel,"cardLogin");
            //return;//tem que vewr se precisa return
        }else{
            for(int i =0 ; i< erroscadlist.size();i++){
                error = erroscadlist.get(i);
                switch(error)
                {
                    case(1):
                        //erro cpf
                        labelCpf.setForeground(Color.red);
                        break;
                    case(2):
                        // error nome
                        labelNomeCompleto.setForeground(Color.red);
                        break;
                    case(7):
                        // erro senha
                        labelSenha.setForeground(Color.red);
                        labelConfirmarSenha.setForeground(Color.red);
                        break;
                }         
            }
        } 
    }//GEN-LAST:event_saveButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
            CardLayout card =  (CardLayout) this.superPanel.getLayout();
            card.show(this.superPanel,"cardLogin");
    }//GEN-LAST:event_voltarButtonActionPerformed

   private void campoFormatadoCpfKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_campoFormatadoCpfKeyTyped
   {//GEN-HEADEREND:event_campoFormatadoCpfKeyTyped
    /*  if(!Character.isDigit(evt.getKeyChar()))
      {
         evt.setKeyChar('\0');
      }
      else
      {
          String textoCampo = campoFormatadoCpf.getText();
          if(textoCampo.length() > 10)
              evt.setKeyChar('\0');
      }*/
   }//GEN-LAST:event_campoFormatadoCpfKeyTyped

   private void campoNomeCompletoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_campoNomeCompletoKeyTyped
   {//GEN-HEADEREND:event_campoNomeCompletoKeyTyped
      // vai dar merda isso aqui
       if(!Character.isLetter(evt.getKeyChar()) && !Character.isWhitespace(evt.getKeyChar()))
      {
         evt.setKeyChar('\0');
      }
   }//GEN-LAST:event_campoNomeCompletoKeyTyped

    private void campoFormatadoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFormatadoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFormatadoCpfActionPerformed

    private ArrayList<Integer> erroscadlist ;
    private boolean errorflag;
    private  MaskFormatter cpfmask; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField campoFormatadoCpf;
    private javax.swing.JTextField campoNomeCompleto;
    private javax.swing.JPasswordField campoPasswordConfirmarSenha;
    private javax.swing.JPasswordField campoPasswordSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JLabel labelConfirmarSenha;
    private static javax.swing.JLabel labelCpf;
    private static javax.swing.JLabel labelNomeCompleto;
    private static javax.swing.JLabel labelSenha;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
  
    
    public static JLabel getLabelCpf()
   {
      return labelCpf;
   }

   public static JLabel getLabelConfirmarSenha()
   {
      return labelConfirmarSenha;
   }

   public static JLabel getLabelNomeCompleto()
   {
      return labelNomeCompleto;
   }

   public static JLabel getLabelSenha()
   {
      return labelSenha;
   }
   public static DefaultFormatterFactory setFormatoData()  
{  
    MaskFormatter comFoco = null;  
    try   
    {   
        comFoco = new MaskFormatter("###.###.###-##");  
    }   
    catch (Exception pe) { }  
    DefaultFormatterFactory factory = new DefaultFormatterFactory(comFoco, comFoco);  
    return factory;  
}  
   
}
