/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentPanel.java
 *
 * Created on 14/06/2013, 13:59:28
 */
package Interface;

/**
 *
 * @author Günther
 */
public class StudentPanel extends javax.swing.JPanel {

    /** Creates new form StudentPanel */
    public StudentPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        newStudentPanel = new javax.swing.JPanel();
        nameStudent = new javax.swing.JLabel();
        fatherStudent = new javax.swing.JLabel();
        motherStudent = new javax.swing.JLabel();
        adressStudent = new javax.swing.JLabel();
        phoneStudent = new javax.swing.JLabel();
        cellphoneStudent = new javax.swing.JLabel();
        birthdayStudent = new javax.swing.JLabel();
        emailStudent = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        motherTextField = new javax.swing.JTextField();
        fatherTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        adressTextField = new javax.swing.JTextField();
        cellphoneTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        birthdaylTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        editStudentPanel = new javax.swing.JPanel();
        nameStudent2 = new javax.swing.JLabel();
        fatherStudent2 = new javax.swing.JLabel();
        motherStudent2 = new javax.swing.JLabel();
        adressStudent2 = new javax.swing.JLabel();
        phoneStudent2 = new javax.swing.JLabel();
        cellphoneStudent2 = new javax.swing.JLabel();
        birthdayStudent2 = new javax.swing.JLabel();
        emailStudent2 = new javax.swing.JLabel();
        motherTextField2 = new javax.swing.JTextField();
        fatherTextField2 = new javax.swing.JTextField();
        phoneTextField2 = new javax.swing.JTextField();
        adressTextField2 = new javax.swing.JTextField();
        cellphoneTextField2 = new javax.swing.JTextField();
        emailTextField2 = new javax.swing.JTextField();
        birthdaylTextField2 = new javax.swing.JTextField();
        studentComboBox = new javax.swing.JComboBox();
        saveStudent = new javax.swing.JButton();
        deleteStudentPanel = new javax.swing.JPanel();
        nameStudentDelete = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        nameStudent.setText("Nome");

        fatherStudent.setText("Nome do Pai");

        motherStudent.setText("Nome da Mãe");

        adressStudent.setText("Endereço");

        phoneStudent.setText("Telefone");

        cellphoneStudent.setText("Celular");

        birthdayStudent.setText("Data de Nascimento");

        emailStudent.setText("E-mail");

        nameTextField.setToolTipText("teste");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        motherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherTextFieldActionPerformed(evt);
            }
        });

        fatherTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        adressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressTextFieldActionPerformed(evt);
            }
        });

        cellphoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellphoneTextFieldActionPerformed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        birthdaylTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdaylTextFieldActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");

        javax.swing.GroupLayout newStudentPanelLayout = new javax.swing.GroupLayout(newStudentPanel);
        newStudentPanel.setLayout(newStudentPanelLayout);
        newStudentPanelLayout.setHorizontalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addComponent(birthdayStudent)
                        .addGap(18, 18, 18)
                        .addComponent(birthdaylTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameStudent)
                            .addComponent(fatherStudent)
                            .addComponent(motherStudent)
                            .addComponent(emailStudent)
                            .addComponent(cellphoneStudent)
                            .addComponent(phoneStudent)
                            .addComponent(adressStudent))
                        .addGap(49, 49, 49)
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fatherTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        newStudentPanelLayout.setVerticalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameStudent)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayStudent)
                    .addComponent(birthdaylTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherStudent)
                    .addComponent(motherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellphoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellphoneStudent))
                .addGap(7, 7, 7)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Aluno", newStudentPanel);

        nameStudent2.setText("Nome");

        fatherStudent2.setText("Nome do Pai");

        motherStudent2.setText("Nome da Mãe");

        adressStudent2.setText("Endereço");

        phoneStudent2.setText("Telefone");

        cellphoneStudent2.setText("Celular");

        birthdayStudent2.setText("Data de Nascimento");

        emailStudent2.setText("E-mail");

        motherTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherTextField2ActionPerformed(evt);
            }
        });

        fatherTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherTextField2ActionPerformed(evt);
            }
        });

        phoneTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextField2ActionPerformed(evt);
            }
        });

        adressTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressTextField2ActionPerformed(evt);
            }
        });

        cellphoneTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellphoneTextField2ActionPerformed(evt);
            }
        });

        emailTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextField2ActionPerformed(evt);
            }
        });

        birthdaylTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdaylTextField2ActionPerformed(evt);
            }
        });

        saveStudent.setText("Salvar");

        javax.swing.GroupLayout editStudentPanelLayout = new javax.swing.GroupLayout(editStudentPanel);
        editStudentPanel.setLayout(editStudentPanelLayout);
        editStudentPanelLayout.setHorizontalGroup(
            editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(birthdayStudent2)
                    .addComponent(nameStudent2)
                    .addComponent(fatherStudent2)
                    .addComponent(motherStudent2)
                    .addComponent(emailStudent2)
                    .addComponent(cellphoneStudent2)
                    .addComponent(phoneStudent2)
                    .addComponent(adressStudent2))
                .addGap(18, 18, 18)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellphoneTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(phoneTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(adressTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(motherTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(fatherTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(emailTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(birthdaylTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStudentPanelLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(saveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        editStudentPanelLayout.setVerticalGroup(
            editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStudentPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameStudent2)
                    .addComponent(studentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayStudent2)
                    .addComponent(birthdaylTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatherStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fatherTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherStudent2)
                    .addComponent(motherTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressStudent2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneStudent2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellphoneTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellphoneStudent2))
                .addGap(7, 7, 7)
                .addGroup(editStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailStudent2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveStudent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar Informações do Aluno", editStudentPanel);

        nameStudentDelete.setText("Nome");

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteStudentPanelLayout = new javax.swing.GroupLayout(deleteStudentPanel);
        deleteStudentPanel.setLayout(deleteStudentPanelLayout);
        deleteStudentPanelLayout.setHorizontalGroup(
            deleteStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentPanelLayout.createSequentialGroup()
                .addGroup(deleteStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deleteStudentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deleteStudentPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(nameStudentDelete)
                        .addGap(48, 48, 48)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        deleteStudentPanelLayout.setVerticalGroup(
            deleteStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteStudentPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(deleteStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameStudentDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Excluir Cadastro do Aluno", deleteStudentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_nameTextFieldActionPerformed

        private void motherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_motherTextFieldActionPerformed

        private void fatherTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_fatherTextFieldActionPerformed

        private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_phoneTextFieldActionPerformed

        private void adressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_adressTextFieldActionPerformed

        private void cellphoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellphoneTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_cellphoneTextFieldActionPerformed

        private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_emailTextFieldActionPerformed

        private void birthdaylTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdaylTextFieldActionPerformed

        // TODO add your handling code here:}//GEN-LAST:event_birthdaylTextFieldActionPerformed

    private void motherTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherTextField2ActionPerformed

    private void fatherTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherTextField2ActionPerformed

    private void phoneTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextField2ActionPerformed

    private void adressTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressTextField2ActionPerformed

    private void cellphoneTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellphoneTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellphoneTextField2ActionPerformed

    private void emailTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField2ActionPerformed

    private void birthdaylTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdaylTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdaylTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adressStudent;
    private javax.swing.JLabel adressStudent2;
    private javax.swing.JTextField adressTextField;
    private javax.swing.JTextField adressTextField2;
    private javax.swing.JLabel birthdayStudent;
    private javax.swing.JLabel birthdayStudent2;
    private javax.swing.JTextField birthdaylTextField;
    private javax.swing.JTextField birthdaylTextField2;
    private javax.swing.JLabel cellphoneStudent;
    private javax.swing.JLabel cellphoneStudent2;
    private javax.swing.JTextField cellphoneTextField;
    private javax.swing.JTextField cellphoneTextField2;
    private javax.swing.JPanel deleteStudentPanel;
    private javax.swing.JPanel editStudentPanel;
    private javax.swing.JLabel emailStudent;
    private javax.swing.JLabel emailStudent2;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JLabel fatherStudent;
    private javax.swing.JLabel fatherStudent2;
    private javax.swing.JTextField fatherTextField;
    private javax.swing.JTextField fatherTextField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel motherStudent;
    private javax.swing.JLabel motherStudent2;
    private javax.swing.JTextField motherTextField;
    private javax.swing.JTextField motherTextField2;
    private javax.swing.JLabel nameStudent;
    private javax.swing.JLabel nameStudent2;
    private javax.swing.JLabel nameStudentDelete;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel newStudentPanel;
    private javax.swing.JLabel phoneStudent;
    private javax.swing.JLabel phoneStudent2;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField phoneTextField2;
    private javax.swing.JButton saveStudent;
    private javax.swing.JComboBox studentComboBox;
    // End of variables declaration//GEN-END:variables
}
