/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dsproject.Escola;
import javax.swing.JLabel;

/**
 *
 * @author pazuti
 */
public class WelcomePanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMessage = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(833, 515));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeMessage.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        welcomeMessage.setText("Bem Vindo ao PRODOWN");
        add(welcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables

public void setWelcomeMessage(String s){
    this.welcomeMessage.setText(s + ", Bem Vindo ao PRODOWN");
}

}
